version: '2'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: john
      POSTGRES_PASSWORD: example
      POSTGRES_DB: endgame
    volumes:
      - dbvolume:/var/lib/postgresql/data
    
  adminer:
    image: adminer
    ports:
      - 8088:8080

  backend:
    image: endgamebackend:v1
    environment:
      DB_USER: john
      DB_PASS: example
      DB: endgame
      DB_HOST: db
    links:
      - db

  frontend:
    image: endgamefrontend:v1
    ports:
      - 8089:5000
    links:
      - backend

volumes:
  dbvolume:
